CREATE DATABASE test_db;

USE test_db;

DROP TABLE IF EXISTS admin;
CREATE TABLE admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    emp_id INT NOT NULL UNIQUE,
    emp_name VARCHAR(255) NOT NULL,
    emp_role VARCHAR(255) NOT NULL,
    
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_updated_by VARCHAR(255),
    deleted_at TIMESTAMP NULL DEFAULT NULL
);