export const LIGHT_THEME_NAME = "lofi";
export const DARK_THEME_NAME = "lofi-dark";

// TODO it's not color anymore, this is a config
export const WIP_OUT_PL_SIZE = [
	{
		key: "f1",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			pl1: "var(--color-primary)",
			pl6: "var(--color-secondary)",
			total_wip: "var(--color-f1color)",
			total_outs: "var(--color-f1color-15)",
			total_lots: "var(--color-f1color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f2",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			pl1: "var(--color-primary)",
			pl6: "var(--color-secondary)",
			total_wip: "var(--color-f2color)",
			total_outs: "var(--color-f2color-15)",
			total_lots: "var(--color-f2color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f3",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			pl1: "var(--color-primary)",
			pl6: "var(--color-secondary)",
			total_wip: "var(--color-f3color)",
			total_outs: "var(--color-f3color-15)",
			total_lots: "var(--color-f3color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "overall",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			pl1: "var(--color-primary)",
			pl6: "var(--color-secondary)",
			total_wip: "var(--color-accent)",
			total_outs: "var(--color-secondary)",
			total_lots: "var(--color-primary)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 2,
		r: 3,
		className: "opacity-100",
	},
];

export const WIP_OUT_CAPACITY = [
	{
		key: "f1",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			capacity: "var(--color-accent)",
			pl1: "var(--color-f1color-pl1)",
			pl6: "var(--color-f1color-pl6)",
			total_wip: "var(--color-f1color)",
			total_outs: "var(--color-f1color-15)",
			total_lots: "var(--color-f1color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f2",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			capacity: "var(--color-accent)",
			pl1: "var(--color-f2color-pl1)",
			pl6: "var(--color-f2color-pl6)",
			total_wip: "var(--color-f2color)",
			total_outs: "var(--color-f2color-15)",
			total_lots: "var(--color-f2color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f3",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			capacity: "var(--color-accent)",
			pl1: "var(--color-f3color-pl1)",
			pl6: "var(--color-f3color-pl6)",
			total_wip: "var(--color-f3color)",
			total_outs: "var(--color-f3color-15)",
			total_lots: "var(--color-f3color-30)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "overall",
		colorVar: {
			wip: "var(--color-primary)",
			out: "var(--color-secondary)",
			capacity: "var(--color-accent)",
			pl1: "var(--color-accent)",
			pl6: "var(--color-secondary)",
			total_wip: "var(--color-accent)",
			total_outs: "var(--color-secondary)",
			total_lots: "var(--color-primary)",
		},
		pl6Dash: "4 4",
		pl6Opacity: 0.55,
		strokeWidth: 2,
		r: 3,
		className: "opacity-100",
	},
];

export const FACTORY_COLORS = [
	{
		key: "f1",
		colorVar: {
			wip: "var(--color-f1color)",
			out: "var(--color-f1color)",
			lots: "var(--color-f1color-15)",
		},
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f2",
		colorVar: {
			wip: "var(--color-f2color)",
			out: "var(--color-f2color)",
			lots: "var(--color-f2color-15)",
		},
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "f3",
		colorVar: {
			wip: "var(--color-f3color)",
			out: "var(--color-f3color)",
			lots: "var(--color-f3color-15)",
		},
		strokeWidth: 1,
		r: 3,
		className: "opacity-100",
	},
	{
		key: "overall",
		colorVar: {
			wip: "var(--color-accent)",
			out: "var(--color-accent)",
			lots: "var(--color-f2color)",
		},
		strokeWidth: 2,
		r: 3,
		className: "opacity-100",
	},
];
